# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-aish"
BBFILE_PATTERN_meta-aish = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-aish = "6"

LAYERDEPENDS_meta-aish = "core"
LAYERSERIES_COMPAT_meta-aish = "blacksail wrynose"
